name: Build Wheels

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - darshan-util/**
      - include/**
      - .github/workflows/build_wheels.yml
  pull_request:
    branches:
      - main
    paths:
      - darshan-util/**
      - include/**
      - .github/workflows/build_wheels.yml
  workflow_dispatch:

jobs:
  get_commit_message:
    name: Get commit message
    runs-on: ubuntu-latest
    if: github.repository == 'darshan-hpc/darshan'
    outputs:
      message: ${{ steps.commit_message.outputs.message }}
    steps:
      - name: Checkout darshan
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v3
        # Gets the correct commit message for pull request
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get commit message
        id: commit_message
        run: |
          set -xe
          COMMIT_MSG=$(git log --no-merges -1 --oneline)
          echo "message=$COMMIT_MSG" >> $GITHUB_OUTPUT
          echo github.ref ${{ github.ref }}

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: get_commit_message
    if: >-
      contains(needs.get_commit_message.outputs.message, '[wheel build]') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-13]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v2

      - name: Build wheels
        uses: pypa/cibuildwheel@298ed2fb2c105540f5ed055e8a6ad78d82dd3a7e # v3.3.1
        with:
          package-dir: ./darshan-util/pydarshan

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
        with:
          name: pydarshan-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          retention-days: 0

  merge_artifacts:
    name: Merge built wheel artifacts
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact/merge@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v4
        with:
          name: pydarshan-wheels-all
