name: End-to-end Testing (regression) Aurora

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - darshan-runtime/**
      - .github/workflows/end_to_end_regression_aurora.yml
  workflow_dispatch:

jobs:
  trigger_alcf_aurora_regression_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch/tag name
        run: echo "GITHUB_REF_NAME=$(echo ${GITHUB_REF} | cut --complement -d/ -f1,2)" >> $GITHUB_ENV
      - uses: eic/trigger-gitlab-ci@1318fa9f4adda50e003db101bc3f9d5ae1b6ab91 # v3
        with:
          url: https://gitlab-ci.alcf.anl.gov
          project_id: 174
          token: ${{ secrets.ALCF_GITLAB_CI_TOKEN_AURORA }}
          variables: |
            GITHUB_REF_NAME="${{ env.GITHUB_REF_NAME }}"
