# Triage PRs based on modified paths
# Rely on .github/pr_path_labeler.yml
# https://github.com/marketplace/actions/labeler
name: "Pull Request Labeler"

permissions:
  contents: read

on:
- pull_request_target

jobs:
  triage-on-file-paths:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/pr_path_labeler.yml"
        sync-labels: true  # remove labels if file not modified anymore
